// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olgquieavfpewbtzceta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sZ3F1aWVhdmZwZXdidHpjZXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzY2NDcsImV4cCI6MjA3MjgxMjY0N30.8F2eEMMEd0bvfzGFfRVklJGLZrNL481ODo4jMjUVTQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});